version: "3"
services:
  frontend:
    build: ./FrontEnd
    volumes:
      - ./FrontEnd:/usr/frontdocker
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - Backend_URL=http://backend:8080

  backend:
    build: ./BackEnd
    volumes:
      - ./BackEnd:/usr/backdocker
    environment:
      database: loizenaidb
      username: postgres
      password: password123
      host: postgres
      dialect: postgres
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_DB: loizenaidb
  